### ISSUE TITLE
.local query

### ISSUE THREAD

**Issue by Frontstriker15** [lathiat/avahi#52] opened 2016-04-09 07:30 UTC
Yesterday i created a small network with VMWare Fusion. But i can't get any RR from my bind via firefox and curl. But dig and nslookup worked... so i found out that avahi made some problems with .local domains. I deactivate it reboot and now everything is working. :D Just as information for you :P

**Comment by Paviluf** [comment] 2016-07-09 09:08
Hello,

I have a problem with Avahi or something related on Fedora 24 because I can't connect to an other Fedora 24 PC by doing this "ssh hostname.local". It work if I do "ssh OtherPCip". I have an android phone with primitive ftpd that allow a ssh connection and I can connect to my phone with "ssh android.local".

It seem that avahi don't show the hostname.local to others computers on Fedora. I also tried to disable the firewall (without rebooting) but it's the same.

I managed to make the connection work from desktop to laptop but that only last for a few minutes. 

How can I make it work ? Is there a bug ?

Thanks !

Reported on Fedora too

https://bugzilla.redhat.com/show_bug.cgi?id=1354080

**Comment by lathiat** [comment] 2017-05-20 07:26
@Frontstriker15 libnss-mdns intentionally black-holes all .local queries.  this is as per specification, however this was fixed in nss-mdns here to try handle that better https://github.com/lathiat/nss-mdns/pull/18

@Paviluf  First two steps to diagnosis would be 
 (1) I would check that libnss-mdns is installed, and then publish the 'hosts' line from /etc/nsswitch.conf
 (2) Try avahi-resolve-host-name hostname.local to see if that works, that will determine if avahi is the issue or the NSS hostname resolution is.
 (3) Include the journal for avahi-daemon

Generally it's not likely a bug in avahi or nss-mdns itself and something you need support from Fedora to fix on your system


Closing this out as the first issue is from nss-mdns and already fixed, the second is a support request and not a bug at this time.

**Closed by lathiat** 2017-05-20 07:26 UTC
