### ISSUE TITLE
Often / permantent Leaving and Joining multicast group... 

### ISSUE THREAD

**Issue by gintonic4all** [lathiat/avahi#342] opened 2021-05-26 21:09 UTC
Hi, 
I'm using avahi-daemon 0.7 on a Raspberry Pi4 with Buster (v10). 
In the syslog I often get a repeating message about leaving and joining multicast group with IPv6 adresses on eth0. 
And in my FritzBox I have set the option to fix the Raspi's IP address. 
Could anybody tell me what this message is about and how to fix the perhaps correspondig problem? It somehow seems to limit the performance of the homebridge service: sometimes event triggers e.g. by switches are not perceived by homebridge, so I guess these syslog messages are associated with this problem. 

--- syslog excerpt:

May 26 22:25:32 homebridge avahi-daemon[364]: Leaving mDNS multicast group on interface eth0.IPv6 with address 2003:d2:1f16:ab00:3a43:c8d1:2b7b:703a.
May 26 22:25:32 homebridge avahi-daemon[364]: Joining mDNS multicast group on interface eth0.IPv6 with address fe80::722:5ee8:f9d1:d083.
May 26 22:25:32 homebridge avahi-daemon[364]: Registering new address record for fe80::722:5ee8:f9d1:d083 on eth0.*.
May 26 22:25:32 homebridge avahi-daemon[364]: Leaving mDNS multicast group on interface eth0.IPv6 with address fe80::722:5ee8:f9d1:d083.
May 26 22:25:32 homebridge avahi-daemon[364]: Joining mDNS multicast group on interface eth0.IPv6 with address 2003:d2:1f16:ab00:3a43:c8d1:2b7b:703a.
May 26 22:25:32 homebridge avahi-daemon[364]: Registering new address record for 2003:d2:1f16:ab00:3a43:c8d1:2b7b:703a on eth0.*.
May 26 22:25:32 homebridge avahi-daemon[364]: Withdrawing address record for fe80::722:5ee8:f9d1:d083 on eth0.
May 26 22:26:46 homebridge avahi-daemon[364]: Withdrawing address record for 2003:d2:1f16:ab00:3a43:c8d1:2b7b:703a on eth0.
May 26 22:26:46 homebridge avahi-daemon[364]: Leaving mDNS multicast group on interface eth0.IPv6 with address 2003:d2:1f16:ab00:3a43:c8d1:2b7b:703a.
May 26 22:26:46 homebridge avahi-daemon[364]: Joining mDNS multicast group on interface eth0.IPv6 with address fd2e:d326:15e:1:f94:5479:14e6:a284.
May 26 22:26:46 homebridge avahi-daemon[364]: Registering new address record for fd2e:d326:15e:1:f94:5479:14e6:a284 on eth0.*.
May 26 22:26:46 homebridge avahi-daemon[364]: Registering new address record for fe80::722:5ee8:f9d1:d083 on eth0.*.
May 26 22:26:46 homebridge avahi-daemon[364]: Withdrawing address record for fd2e:d326:15e:1:f94:5479:14e6:a284 on eth0.
May 26 22:26:46 homebridge avahi-daemon[364]: Leaving mDNS multicast group on interface eth0.IPv6 with address fd2e:d326:15e:1:f94:5479:14e6:a284.
May 26 22:26:46 homebridge avahi-daemon[364]: Joining mDNS multicast group on interface eth0.IPv6 with address fe80::722:5ee8:f9d1:d083.
May 26 22:26:46 homebridge avahi-daemon[364]: Leaving mDNS multicast group on interface eth0.IPv6 with address fe80::722:5ee8:f9d1:d083.
May 26 22:26:46 homebridge avahi-daemon[364]: Joining mDNS multicast group on interface eth0.IPv6 with address fd2e:d326:15e:1:f94:5479:14e6:a284.
May 26 22:26:46 homebridge avahi-daemon[364]: Registering new address record for fd2e:d326:15e:1:f94:5479:14e6:a284 on eth0.*.
May 26 22:26:46 homebridge avahi-daemon[364]: Registering new address record for 2003:d2:1f16:ab00:3a43:c8d1:2b7b:703a on eth0.*.
May 26 22:26:46 homebridge avahi-daemon[364]: Withdrawing address record for fd2e:d326:15e:1:f94:5479:14e6:a284 on eth0.
May 26 22:26:46 homebridge avahi-daemon[364]: Withdrawing address record for fe80::722:5ee8:f9d1:d083 on eth0.

-----
Update: meanwhile I've deactived IPv6 in the avahi-config. Restarting avahi-daemon this message occurs:

May 26 23:13:25 homebridge avahi-daemon[31234]: Successfully called chroot().
May 26 23:13:25 homebridge avahi-daemon[31234]: Successfully dropped remaining capabilities.
May 26 23:13:25 homebridge avahi-daemon[31234]: No service file found in /etc/avahi/services.
**May 26 23:13:25 homebridge avahi-daemon[31234]: ***** WARNING: Detected another IPv4 mDNS stack running on this host. This makes mDNS unreliable and is thus not recommende****
May 26 23:13:25 homebridge avahi-daemon[31234]: Joining mDNS multicast group on interface eth0.IPv4 with address 192.168.178.113.
May 26 23:13:25 homebridge avahi-daemon[31234]: New relevant interface eth0.IPv4 for mDNS.
May 26 23:13:25 homebridge avahi-daemon[31234]: Network interface enumeration completed.
May 26 23:13:25 homebridge avahi-daemon[31234]: Registering new address record for 2003:d2:1f16:ab00:3a43:c8d1:2b7b:703a on eth0.*.
May 26 23:13:25 homebridge avahi-daemon[31234]: Registering new address record for 192.168.178.113 on eth0.IPv4.
May 26 23:13:25 homebridge avahi-daemon[31234]: Server startup complete. Host name is homebridge.local. Local service cookie is 1150634006.

So.... how do I have another mdns stack? I've also installed pihole in a quite convenient way. Could this lead to this problem? How should I analyze this? 

Thanks for any help and hints. 

Best regards,
Matthias

**Comment by lathiat** [comment] 2021-05-27 01:27
This is a bug I've seen a couple of times but not tracked down. An avahi-daemon restart will stop it. I have a suspicion it may be due to time going backwards but haven't really proven that.

**Comment by gintonic4all** [comment] 2021-05-27 18:20
Yeah, I thought so, too. But, after restarting this bug occurs again - after serval minutes (about 10 - 20 min) running properly. :-/ 
And I still couldn't figure out what this warning is about... any idea?

**Comment by mvduin** [comment] 2021-12-01 14:24
try setting `publish-aaaa-on-ipv4=no`

**Comment by mvduin** [comment] 2021-12-01 14:28
Or, if it's indeed related to system time changes then #96 should properly fix the problem (as opposed to disabling IPv6 support entirely which is of course an ugly workaround)

**Comment by adriancable** [comment] 2022-01-18 17:46
@gintonic4all - did you ever get a resolution on this? I'm experiencing a similar thing, and I have applied all relevant PRs and patches to my Avahi (including #96) with no effect.

When this happens, Avahi expires the AAAA records (sending out an announcement with TTL 0) and then immediately afterwards re-announces (with TTL 120). This happens every few minutes.

@lathiat - any ideas on this? What in general makes Avahi decide to withdraw an address record on an interface?

Jan 18 09:42:46 avahi-daemon[362]: Withdrawing address record for fdb9:879d:36:4a2d:7cf7:f8f:3d9e:ab on eth0.
Jan 18 09:42:46 avahi-daemon[362]: Leaving mDNS multicast group on interface eth0.IPv6 with address fdb9:879d:36:4a2d:7cf7:f8f:3d9e:ab.
Jan 18 09:42:46 avahi-daemon[362]: Joining mDNS multicast group on interface eth0.IPv6 with address 2601:646:c500:283c:c739:a4e9:478d:fd68.
Jan 18 09:42:46 avahi-daemon[362]: Withdrawing address record for fd23:bae9:2bf5:1:c504:7f55:44b9:d89c on eth0.
Jan 18 09:42:46 avahi-daemon[362]: Withdrawing address record for 2601:646:c500:283c:c739:a4e9:478d:fd68 on eth0.
Jan 18 09:42:46 avahi-daemon[362]: Leaving mDNS multicast group on interface eth0.IPv6 with address 2601:646:c500:283c:c739:a4e9:478d:fd68.
Jan 18 09:42:46 avahi-daemon[362]: Joining mDNS multicast group on interface eth0.IPv6 with address fe80::4177:4744:b79d:933e.
Jan 18 09:42:46 avahi-daemon[362]: Leaving mDNS multicast group on interface eth0.IPv6 with address fe80::4177:4744:b79d:933e.
Jan 18 09:42:46 avahi-daemon[362]: Joining mDNS multicast group on interface eth0.IPv6 with address fd23:bae9:2bf5:1:c504:7f55:44b9:d89c.
Jan 18 09:42:46 avahi-daemon[362]: Registering new address record for fd23:bae9:2bf5:1:c504:7f55:44b9:d89c on eth0.*.
Jan 18 09:42:46 avahi-daemon[362]: Registering new address record for 2601:646:c500:283c:c739:a4e9:478d:fd68 on eth0.*.
Jan 18 09:42:46 avahi-daemon[362]: Registering new address record for fdb9:879d:36:4a2d:7cf7:f8f:3d9e:ab on eth0.*.
Jan 18 09:42:46 avahi-daemon[362]: Withdrawing address record for fd23:bae9:2bf5:1:c504:7f55:44b9:d89c on eth0.
Jan 18 09:42:46 avahi-daemon[362]: Leaving mDNS multicast group on interface eth0.IPv6 with address fd23:bae9:2bf5:1:c504:7f55:44b9:d89c.
Jan 18 09:42:46 avahi-daemon[362]: Joining mDNS multicast group on interface eth0.IPv6 with address fdb9:879d:36:4a2d:7cf7:f8f:3d9e:ab.
Jan 18 09:42:46 avahi-daemon[362]: Withdrawing address record for 2601:646:c500:283c:c739:a4e9:478d:fd68 on eth0.
Jan 18 09:42:46 avahi-daemon[362]: Withdrawing address record for fdb9:879d:36:4a2d:7cf7:f8f:3d9e:ab on eth0.
Jan 18 09:42:46 avahi-daemon[362]: Leaving mDNS multicast group on interface eth0.IPv6 with address fdb9:879d:36:4a2d:7cf7:f8f:3d9e:ab.
Jan 18 09:42:46 avahi-daemon[362]: Joining mDNS multicast group on interface eth0.IPv6 with address fe80::4177:4744:b79d:933e.
Jan 18 09:42:46 avahi-daemon[362]: Leaving mDNS multicast group on interface eth0.IPv6 with address fe80::4177:4744:b79d:933e.
Jan 18 09:42:46 avahi-daemon[362]: Joining mDNS multicast group on interface eth0.IPv6 with address fdb9:879d:36:4a2d:7cf7:f8f:3d9e:ab.
Jan 18 09:42:46 avahi-daemon[362]: Registering new address record for fdb9:879d:36:4a2d:7cf7:f8f:3d9e:ab on eth0.*.
Jan 18 09:42:46 avahi-daemon[362]: Registering new address record for fd23:bae9:2bf5:1:c504:7f55:44b9:d89c on eth0.*.
Jan 18 09:42:46 avahi-daemon[362]: Registering new address record for 2601:646:c500:283c:c739:a4e9:478d:fd68 on eth0.*.

**Comment by mvduin** [comment] 2022-01-19 00:27
@adriancable If avahi is receiving RTM_DELADDR followed by RTM_NEWADDR then your machine is genuinely losing and regaining its IPv6 address, and in particular this isn't a bug in avahi, nor does it sound likely to be a bug in the Ethernet driver. Try sniffing your network for IPv6 router solicitation messages to see what's going on.

**Comment by adriancable** [comment] 2022-01-19 00:37
@mvduin - absolutely clear that this isn't a bug in avahi per se, assuming what I am seeing is the same issue as reported by the OP (and it does look so).

It isn't clear to me that "concealing" the impact of this issue on Avahi is necessary the wrong thing, if the underlying issue is widespread and it turns out there isn't a ready workaround for that.

I will do some sniffing to see if I can shed more light on what is actually going on.

**Comment by adriancable** [comment] 2022-01-19 00:45
@mvduin - one other note. I can trigger this happening by doing `rdisc6 eth0`, so it is definitely related to router solicitations.

I don't have a lot of experience with different IPv6-capable routers. Presumably it is not normal for a router to drop and then re-add IPv6 addresses when it receives a router solicitation message.

I am using an Eero 6 Pro - I wonder what router the OP is using, and if it's a router bug. @gintonic4all ?

**Comment by mvduin** [comment] 2022-01-19 00:48
@adriancable Well apparently there also are or have been avahi bugs that caused messages like these, but in your case (and that of various other people) it looks more like a router on your network is causing mayhem and Avahi is merely making this issue visible, and even if you stop Avahi from making noise about it, there will still be issues. See also for example [here](https://github.com/lathiat/avahi/issues/41#issuecomment-757558134) where people reported it also resulted in Google Chrome occasionally interrupting loading the page because "the network has changed".

**Comment by adriancable** [comment] 2022-01-19 00:54
@mvduin - hmm, I'm not sure if what I am seeing is exactly the same as your [example](https://github.com/lathiat/avahi/issues/41#issuecomment-757558134). In that case, I think your conclusion of the OP's issue seems to have been caused by preferred_lft falling to 0, with no RA being sent before that happens. That definitely isn't the case for me - my shortest preferred_lft in `ip -6 address` is 30 minutes and I am seeing these messages at much more frequent intervals. Then there was another poster where the issue seems to have been caused by a faulty dnsmasq configuration. (I'm not using dnsmasq or anything similar.)

**Comment by mvduin** [comment] 2022-01-19 01:09
@adriancable No it's not the exact same issue, I also never said it was nor meant to imply so. It was merely another example of problems with IPv6 connectivity being misdiagnosed as an Avahi problem because it was logging about it. In their case, dnsmasq was generating faulty router solicitations.

**Comment by california444** [comment] 2022-03-30 21:23
Hi,
I observed the same problem. Log entries about withdrawing and registering address records seemed to correspond with router advertisement messages in my case.
What helped for me was to change from stateless address configuration to DHCPv6. Since I activated DHCPv6 receiving router advertisement messages no longer lead to withdrawing and registering new address records.

**Comment by adriancable** [comment] 2022-03-30 21:33
@california444 - yes, that makes sense.

What I did in my case is to modify Avahi to simply defer all address withdrawals by 250ms. If a registration of a new record comes in for an address that's in the defer list, we simply cancel the withdrawal. Otherwise, we withdraw the record after the 250ms timer has expired.

Since the gap between withdrawal and registration after a RAM was around ~10ms for me, the 250ms I allow is quite a reasonable margin and I don't think that a general 250ms delay in address record withdrawal will cause any practical issues.

Looking at logs for the last couple of months, this works around the issue 100% without introducing any side effects.

Yes, purists will say this isn't an Avahi issue blah blah blah but actually, we live in the real world which is full of product X working around issues in product Y. We can fix Avahi more quickly than we can beg router manufacturers to fix their own firmware.

**Comment by mvduin** [comment] 2022-03-31 04:51
@adriancable Depends on whether the RA is actually handled by the kernel or by a network manager in userspace, e.g. systemd-networkd disables the kernel's RA handling (`/proc/sys/net/ipv6/conf/$INTERFACE/accept_ra` is set to zero), but dunno what other network managers do.

**Comment by adriancable** [comment] 2022-03-31 04:56
Interesting. On our device, which uses NetworkManager, `/proc/sys/net/ipv6/conf/*/accept_ra` is 1.

**Comment by mvduin** [comment] 2022-03-31 05:30
Yep. It also means that people with the same problem could try using systemd-networkd as network manager as a workaround, if it suits their use-case (e.g. embedded or server more likely than desktop, although I personally do also use it on my laptop).

Trivial config for the lazy (save as `/etc/systemd/network/99-default.network`):
```ini
# fallback config for any interface other than loopback
[Match]
Type=!loopback

[Network]
# enable DHCPv4.  note that IPv6 by default uses RA, which will trigger DHCPv6 automatically if needed
DHCP=ipv4

# optional: use dns search domain(s) provided by dhcp and RA
[DHCP]
UseDomains=yes
[IPv6AcceptRA]
UseDomains=yes
```

**Comment by evverx** [comment] 2023-10-03 11:14
Looks like avahi is just the messenger here. It should be fixed in whatever manages network interfaces like that. Closing.

**Closed by evverx** 2023-10-03 11:14 UTC
