### ISSUE TITLE
Requiring service to be on D-Bus

### ISSUE THREAD

**Issue by zeenix** [lathiat/avahi#114] opened 2017-04-15 12:20 UTC
From my TCP service, I'm making the appropriate D-Bus calls to Avahi to get it advertised on the network. Avahi tells my service all is fine but immediately after it realizes that my service is not a D-Bus service, as you can see from the `busctl monitor` output below:

```
‣ Type=method_call  Endian=l  Flags=0  Version=1  Priority=0 Cookie=2
  Sender=:1.165  Destination=org.freedesktop.Avahi  Path=/  Interface=org.freedesktop.Avahi.Server  Member=EntryGroupNew
  UniqueName=:1.165
  MESSAGE "" {
  };

‣ Type=method_return  Endian=l  Flags=1  Version=1  Priority=0 Cookie=51  ReplyCookie=2
  Sender=:1.4  Destination=:1.165
  UniqueName=:1.4
  MESSAGE "o" {
          OBJECT_PATH "/Client5/EntryGroup1";
  };

‣ Type=method_call  Endian=l  Flags=0  Version=1  Priority=0 Cookie=2
  Sender=:1.166  Destination=org.freedesktop.Avahi  Path=/Client5/EntryGroup1  Interface=org.freedesktop.Avahi.EntryGroup  Member=AddService
  UniqueName=:1.166
  MESSAGE "iiussssqs" {
          INT32 -1;
          INT32 -1;
          UINT32 0;
          STRING "gps-share";
          STRING "_nmea-0183._tcp";
          STRING "";
          STRING "";
          UINT16 46403;
          STRING "";
  };

‣ Type=method_call  Endian=l  Flags=0  Version=1  Priority=0 Cookie=3
  Sender=:1.166  Destination=org.freedesktop.Avahi  Path=/Client5/EntryGroup1  Interface=org.freedesktop.Avahi.EntryGroup  Member=Commit
  UniqueName=:1.166
  MESSAGE "" {
  };

‣ Type=error  Endian=l  Flags=1  Version=1  Priority=0 Cookie=52  ReplyCookie=2
  Sender=:1.4  Destination=:1.166
  ErrorName=org.freedesktop.DBus.Error.AccessDenied  ErrorMessage="Access denied"
  UniqueName=:1.4
  MESSAGE "s" {
          STRING "Access denied";
  };

‣ Type=error  Endian=l  Flags=1  Version=1  Priority=0 Cookie=13  ReplyCookie=52
  Sender=org.freedesktop.DBus  Destination=:1.4
  ErrorName=org.freedesktop.DBus.Error.ServiceUnknown  ErrorMessage="The name :1.166 was not provided by any .service files"
  MESSAGE "s" {
          STRING "The name :1.166 was not provided by any .service files";
  };

‣ Type=error  Endian=l  Flags=1  Version=1  Priority=0 Cookie=53  ReplyCookie=3
  Sender=:1.4  Destination=:1.166
  ErrorName=org.freedesktop.DBus.Error.AccessDenied  ErrorMessage="Access denied"
  UniqueName=:1.4
  MESSAGE "s" {
          STRING "Access denied";
  };

‣ Type=error  Endian=l  Flags=1  Version=1  Priority=0 Cookie=14  ReplyCookie=53
  Sender=org.freedesktop.DBus  Destination=:1.4
  ErrorName=org.freedesktop.DBus.Error.ServiceUnknown  ErrorMessage="The name :1.166 was not provided by any .service files"
  MESSAGE "s" {
          STRING "The name :1.166 was not provided by any .service files";
  };

```
I'm not sure this is expected behaviour and I'm missing something or a bug but I failed to find answers so I thought I file an issue and see how it goes from there. I'm on Fedora 25 with Avahi 0.6.32.

**Comment by zeenix** [comment] 2017-04-15 16:24
@lathiat you asked for code on twitter. Here it is: https://github.com/zeenix/gps-share/blob/wip/avahi/src/avahi.rs . Should be very easy to put that in a standalone .rs file to test but if you need me to do that, let me know.

**Comment by zeenix** [comment] 2017-04-15 20:33
I've a theory of what's going on. I'm not keeping the the dbus connection objects around and hence the when connection is closed on my side soon after object gets disposed, Avahi detects that and tries to restart the service and it fails, and then gives up. Is that possible?

I tried to modify the code to keep the connection objects but ran into a few hard-to-solve issues with borrowing in Rust.

**Comment by zeenix** [comment] 2017-04-15 21:19
I managed to keep my dbus connection objects alive and seems I managed to get rid of this one:

```
‣ Type=error  Endian=l  Flags=1  Version=1  Priority=0 Cookie=16  ReplyCookie=56
  Sender=org.freedesktop.DBus  Destination=:1.4
  ErrorName=org.freedesktop.DBus.Error.ServiceUnknown  ErrorMessage="The name :1.182 was not provided by any .service files"
  MESSAGE "s" {
          STRING "The name :1.182 was not provided by any .service files";
  };

```

**Comment by zeenix** [comment] 2017-04-15 21:20
I get the AccessDenied in the log even if I run my service as root. What gives?

**Comment by lathiat** [comment] 2017-04-17 08:23
OK so what is happening here, is the dbus-macros-rs package is creating a new private D-BUS connection for each object it implements.  So when speaking with the "Server" to run EntryGroupNew and the "EntryGroup" that is created, a different dbus owner speaks to the daemon.  Since they don't match, the calls are rejected with access denied.  This is not a bug in Avahi but requires a better client implementation.

The fix is to share a connection between the two objects.  I made a start at trying to do that here but I don't know enough rust yet to get it working fully.. Will have to experiment some more.

I think either we can try to join this connection to the lifetime ('a') or create some kind of over-all object to hold the Server and EntryGroup which owns the connection.

https://github.com/lathiat/gps-share/tree/wip/avahi

**Comment by zeenix** [comment] 2017-04-17 11:08
> OK so what is happening here, is the dbus-macros-rs package is creating a new private D-BUS connection for each object it implements. So when speaking with the "Server" to run EntryGroupNew and the "EntryGroup" that is created, a different dbus owner speaks to the daemon. Since they don't match, the calls are rejected with access denied. This is not a bug in Avahi but requires a better client implementation.

Thanks @lathiat . You're very much correct that dbus-macros need to be changed to fix the real issue but this I think this exposes two issues in avahi:

* The proper (de-facto standard) way of returning errors is to return error from the method itself that was incorrectly called, rather than returning successfully from the calls and then later sending an error.

* The error is very vague. It would have been much easier to debug this issue if it had some details.

> The fix is to share a connection between the two objects. I made a start at trying to do that here but I don't know enough rust yet to get it working fully.. Will have to experiment some more.
> 
> I think either we can try to join this connection to the lifetime ('a') or create some kind of over-all object to hold the Server and EntryGroup which owns the connection.
> 
> https://github.com/lathiat/gps-share/tree/wip/avahi

Thanks so much for taking the time to provide a fix. I'll look into it but I'm not much of a Rust expert either but @antoyo would likely know better.

**Comment by zeenix** [comment] 2017-04-17 12:28
dbus-macros issue fixed: https://github.com/antoyo/dbus-macros-rs/issues/20

**Comment by lathiat** [comment] 2017-04-27 04:42
Closing this out

**Closed by lathiat** 2017-04-27 04:42 UTC
Labels: invalid

**Comment by zeenix** [comment] 2017-04-27 09:28
@lathiat what about the two issues this exposed, as I described in my last comment?

**Comment by zeenix** [comment] 2017-05-04 13:39
@lathiat ping? Do you want me to file separate bugs for those issues?

**Comment by zeenix** [comment] 2017-05-16 11:08
OK, so I filed #121 and #122 for issues identified here, with former being the most important IMO.
