### ISSUE TITLE
New version, 0.9 ?

### ISSUE THREAD

**Issue by Neustradamus** [lathiat/avahi#325] opened 2021-02-20 22:22 UTC
Hello,

It is possible to have a 0.9 with all improvements since 0.8?

Thanks in advance.

**Comment by evverx** [comment] 2023-06-04 19:00
https://github.com/lathiat/avahi/issues/430 is technically a duplicate of this issue but it seems that that issue is more active so I'll go ahead and close this in favor of https://github.com/lathiat/avahi/issues/430.

**Closed by evverx** 2023-06-04 19:00 UTC

**Comment by Neustradamus** [comment] 2023-10-29 17:31
After this closed ticket and the second one from @ilkery (https://github.com/lathiat/avahi/issues/430), I have done a ticket about all current CVEs since 2021, security is important, a new release is always requested:
- https://github.com/lathiat/avahi/issues/503
