### ISSUE TITLE
[Feature Request] /etc/avahi/hosts ability to reference ip by interface/all interfaces

### ISSUE THREAD

**Issue by ava-dylang** [lathiat/avahi#109] opened 2017-03-28 18:16 UTC
Setting up multiple host aliases is a constant desire, I would really love a built-in way to ask for a second alias of the current machine, probably with that ip being identified by a specific adapter.

**Comment by ava-dylang** [comment] 2017-03-29 19:18
Ah, I've just realized that when I caved and hard coded it, I get the error reported in https://github.com/lathiat/avahi/issues/40 :\ Damn, why cant the debian people package the avahi-aliases package already.

**Comment by lathiat** [comment] 2017-05-20 08:57
Closing as duplicate of #40, added comment about not needing to specify the IP.

**Closed by lathiat** 2017-05-20 08:57 UTC
Labels: duplicate, enhancement
