### ISSUE TITLE
avahi stops working with reflect-filters=..

### ISSUE THREAD

**Issue by dMopp** [lathiat/avahi#433] opened 2023-01-09 15:16 UTC
Hi, i using avahi and when i set the following filters:

`reflect-filters=_airplay._tcp,_hap._tcp,_home-assistant._tcp,_hue._tcp,_ipp._tcp,_ipps._tcp,_mieleathome._tcp,_pdl-datastream._tcp,_print-caps._tcp,_printer._tcp,_raop._tcp,_rdlink._tcp,_scanner._tcp,_sleep-proxy._udp,_spotify-connect._tcp,_uscan._tcp,_companion-link._tcp` it stops working while when i set 
`reflect-filters=_airplay._tcp,_hap._tcp,_home-assistant._tcp,_hue._tcp,_ipp._tcp,_ipps._tcp,_mieleathome._tcp,_pdl-datastream._tcp,_print-caps._tcp,_printer._tcp,_raop._tcp,_rdlink._tcp,_scanner._tcp,_sleep-proxy._udp,_spotify-connect._tcp,_uscan._tcp`
it works just fine.

I can exchange the last entry if i want, so i guess there is a number of character limitation somehow (256Chars)? Can this be extended or can a blacklist instead of a whitelist been added ? thanks !

**Comment by evverx** [comment] 2023-06-04 19:16
Looks like it's a duplicate of https://github.com/lathiat/avahi/issues/315.

**Closed by evverx** 2023-06-04 19:16 UTC
Labels: duplicate
