### ISSUE TITLE
Spurious host name conflict on link up

### ISSUE THREAD

**Issue by mvduin** [lathiat/avahi#193] opened 2018-08-14 23:18 UTC
We've noticed on our devices that avahi-daemon (0.7) occasionally reports a bogus hostname conflict during address registration on link up:

```
Aug 15 00:55:42.523413 nena systemd-networkd[6295]: eth0: Gained carrier
Aug 15 00:55:42.544560 nena systemd-networkd[6295]: eth0: DHCPv4 address 10.0.31.27/24 via 10.0.31.1
Aug 15 00:55:42.580169 nena avahi-daemon[6760]: Joining mDNS multicast group on interface eth0.IPv4 with address 10.0.31.27.
Aug 15 00:55:42.622468 nena avahi-daemon[6760]: New relevant interface eth0.IPv4 for mDNS.
Aug 15 00:55:42.623752 nena avahi-daemon[6760]: Registering new address record for 10.0.31.27 on eth0.IPv4.
Aug 15 00:55:42.707321 nena avahi-daemon[6760]: Leaving mDNS multicast group on interface eth0.IPv6 with address fe80::a2f6:fdff:fe4c:1a1d.
Aug 15 00:55:42.737255 nena avahi-daemon[6760]: Joining mDNS multicast group on interface eth0.IPv6 with address 2001:981:5f7c:1:a2f6:fdff:fe4c:1a1d.
Aug 15 00:55:42.757235 nena avahi-daemon[6760]: Registering new address record for 2001:981:5f7c:1:a2f6:fdff:fe4c:1a1d on eth0.*.
Aug 15 00:55:42.758635 nena avahi-daemon[6760]: Withdrawing address record for fe80::a2f6:fdff:fe4c:1a1d on eth0.
Aug 15 00:55:42.772765 nena avahi-daemon[6760]: Withdrawing address record for 10.0.31.27 on eth0.
Aug 15 00:55:42.775084 nena avahi-daemon[6760]: Host name conflict, retrying with nena-2
Aug 15 00:55:42.776372 nena avahi-daemon[6760]: Registering new address record for 2001:981:5f7c:1:a2f6:fdff:fe4c:1a1d on eth0.*.
Aug 15 00:55:42.777538 nena avahi-daemon[6760]: Registering new address record for 10.0.31.27 on eth0.IPv4.
Aug 15 00:55:44.589421 nena avahi-daemon[6760]: Server startup complete. Host name is nena-2.local. Local service cookie is 2846163560.
Aug 15 00:55:48.023763 nena systemd-networkd[6295]: eth0: Configured
```

I can reproduce it fairly easily by repeatedly disconnecting ethernet and plugging it back, and both avahi-daemon 0.6.32 (debian stable) and 0.7 (debian testing) are affected. The problem appears to be fixed if I set `publish-aaaa-on-ipv4=no` in avahi-daemon.conf.

**Comment by marc-h38** [comment] 2020-05-03 01:17
Duplicate of #117 , please close.

**Closed** 2021-11-30 07:51 UTC
