### ISSUE TITLE
Please read comments on commits

### ISSUE THREAD

**Issue by Neustradamus** [lathiat/avahi#335] opened 2021-04-11 15:50 UTC
@andhe and @lathiat: Please read comments:

From @rworkman:
- https://github.com/lathiat/avahi/commit/751be804e891aec5701a059144e2f5cbfc981b36

------------------

@merwok: Please read comments:

From @angrysoft and @JuanScerriE:
- https://github.com/lathiat/avahi/commit/a94f72081dd1d546a1d95d860311a1242315bb28

And any news for a 0.9 release?

**Comment by merwok** [comment] 2021-04-11 23:41
I ignored that comment, as it’s misguided (python way is `isinstance`) and unneeded.

**Comment by JuanScerriE** [comment] 2021-04-12 15:23
@merwok whose comment did you ignore, mine or @angrysoft? Nevertheless, the modification you made broke avahi-discover, at least for me. I do not understand why you added .decode in the first place for something which is already a string. Could you explain? By the way I am not sure if you saw but the in the photos which I uploaded I removed completely removed your additions and avahi-discover worked as expected.

I do not think that my photo actually depicted the error properly. Basically, when you click on one of the many services in avahi-discover you should get information regarding the service. What was happening was that due to the .decode the python interpreter would send an error and not display the required information (service name, service type etc).

Regards.

**Comment by merwok** [comment] 2021-04-12 16:03
The change was from before Python 3 support.  Read comments starting at https://github.com/lathiat/avahi/pull/270#issuecomment-617210225

Avahi could/should switch to Python 3 only, and could then remove compatibility measures and Python 2-specific code.

**Comment by angrysoft** [comment] 2021-04-12 16:15
My comment was a simple workaround. I didn't search for a source of the
problem. The problem is that you treat a string  list as a bytes list  when
you look at self.update_lablel call last argument is string
array avahi.txt_array_to_string_array(txt) .

pon., 12 kwi 2021 o 17:23 JuanScerriE ***@***.***> napisał(a):

**Comment by evverx** [comment] 2023-06-04 17:55
As far as I can tell those issues were addressed in git (in https://github.com/lathiat/avahi/pull/282 and https://github.com/lathiat/avahi/pull/142). The next release is kind of discussed in https://github.com/lathiat/avahi/issues/430. I'll go ahead and close this.

**Closed by evverx** 2023-06-04 17:55 UTC

**Comment by Neustradamus** [comment] 2023-06-04 18:00
@evverx: Have you seen this issue too from @rworkman?
- https://github.com/lathiat/avahi/issues/311

**Comment by evverx** [comment] 2023-06-04 18:06
Yes I have. According to https://github.com/lathiat/avahi/issues/311#issuecomment-735657247

> This seems fine in git

I did't close it though. Either way that issue is open and there is no need to keep reporting the same issues over and over again.
