### ISSUE TITLE
Enhancement: Is it possible to create aliases of the hostname?

### ISSUE THREAD

**Issue by Dweller** [lathiat/avahi#319] opened 2021-01-18 16:23 UTC
There seems to be a restriction/limitation on the current avahi-daemon implementation that there can only be a single hostname per IP address.  (So adding multiple entries in /etc/avahi/hosts with the same IP address causes errors).

Would it be possible to add aliases for the main hostname?

e.g. if your hostname was for example myserver.local could aliases like www, smtp, etc. be configured?

Thus is myserver.local had a IP address of 192.168.0.99 the avahi-daemon would advertise and www.myserver.local and smtp.myserver.local as the same IP address (192.168.0.99).

They would all reference the main hostname IP address but this would mean that daemons that support virtual hosts would then be able to support multiple destinations.    This could be accomplished by a alias-names in the avahi-daemon.conf file.    But perhaps a flag in the .service file could also enable an alias?.

The reason this is useful is because it allows multiple destinations to be configured on a single IP address.

e.g. in nginx I eould configure:-
server {
    listen 80;
    server_name www.myserver.local;
    location / {
        root /var/www/html;
        try_files $uri $uri/ =404;
    }
} 

server {
   listen 80;;
   server_name test.myserver.local;
   location / {
        root /var/www/test;;
        try_files $uri $uri/ =404;
    }
}

Similar functionality exists for most smtp servers..

Thanks in advance.

**Comment by evverx** [comment] 2023-11-10 03:35
Looks like it's a duplicate of https://github.com/lathiat/avahi/issues/40.

There are links to various scripts there allowing publishing CNAMEs using the "AddRecord" D-Bus method. I'm not sure whether those scripts still work but the go script was mentioned several months ago so unlike the python script it's up to date probably.

**Closed by evverx** 2023-11-10 03:35 UTC
