### ISSUE TITLE
Avahi-browse can't get notified when service's IP address was changed

### ISSUE THREAD

**Issue by briancui** [lathiat/avahi#196] opened 2018-08-29 09:29 UTC
I start an avahi-browse for discovering peer applications on the network. The application is running on Ubuntu 16.04.5. The application is using IPv4 (I use dns-sd to simulate)

I've noticed that when a peer application's host IP address was changed, avahi-browse doesn't get any updated information.

I can reproduce this via:
1. Host 1: run dns-sd -R probe _xcom._tcp local 443 &
2. Host 2: run avahi-browse -r _xcom._tcp
3. Change IP address of Host 1: from DHCP to static, and on Host 2, there isn't any update.

Using dbus-monitor (dbus-monitor --system "sender='org.freedesktop.Avahi'"), I can't see the message being sent to the avahi-browse with the new IP address.

At the same if I run "dns-sd -Q probe.local 1 1" on Host 3, then I can see Rmv/Add broadcasts in sequence.

![image](https://user-images.githubusercontent.com/1028954/44779049-066a7000-abb1-11e8-8562-453529c08e48.png)

The avahi version is 0.6.32~rc+dfsg-1ubuntu2.2

Is it a bug?

**Comment by briancui** [comment] 2018-09-21 07:19
@lathiat are you able to take a look at this issue? Appreciated.

**Comment by zonque** [comment] 2020-10-16 12:26
The address of that service is only looked up once by `avahi-browse`, and the `ServiceResolver` is then thrown away. If you implement that logic yourself using the D-Bus API, you can just keep the `ServiceResolver` around and wait for the `Found` signal to be emitted, which will then update you on any IP address change.

**Comment by pemensik** [comment] 2023-03-28 16:54
I think this should be handled. If the host has changed its own IP and no longer is listening on IP it published services on, it should publish new services again. Just on new IP.

I think this issue has two parts:
- Is Host1 sending new announces of the service after the interface has changed address(es)?
- Is browse-avahi able to catch and present those change in existing services? Can it remove old and add a new with different IP?

**Comment by evverx** [comment] 2023-11-10 00:29
Looks like it's a duplicate of https://github.com/lathiat/avahi/issues/95. Closing.

**Closed by evverx** 2023-11-10 00:29 UTC
