### ISSUE TITLE
Missing build-db file in avahi-0.8 tarball ?

### ISSUE THREAD

**Issue by saxa** [lathiat/avahi#277] opened 2020-04-10 13:24 UTC
Hi I just tried to build the latest avahi downloaded from the avahi website and I get this error:

`
Making all in service-type-database
make[2]: Entering directory '/mnt/space1/DLG/work/avahi-0.8-1/avahi-0.8/service-type-database'
make[2]: *** No rule to make target 'build-db', needed by 'all-am'.  Stop.
make[2]: Leaving directory '/mnt/space1/DLG/work/avahi-0.8-1/avahi-0.8/service-type-database'
make[1]: *** [Makefile:825: all-recursive] Error 1
make[1]: Leaving directory '/mnt/space1/DLG/work/avahi-0.8-1/avahi-0.8'
make: *** [Makefile:735: all] Error 2
Error!  make exited with status: 2
Failed package avahi
`
Seems that build-db script is missing in my service-type-database/ directory.

`
root@braserv:/home/sasa/DEVELOPMENT/DLG_3_36# ls /mnt/space1/DLG/work/avahi-0.8-1/avahi-0.8/service-type-database/
Makefile  Makefile.am  Makefile.in  service-types
`

**Comment by saxa** [comment] 2020-04-10 13:26
I can see that the github tree has it in.

**Comment by saxa** [comment] 2020-04-10 13:31
I confirm that by manually adding this file into the system-type-database/ the build finishes normally.

**Comment by rworkman** [comment] 2020-11-02 04:12
Also fixes #298 (dupe of this report)

**Closed** 2023-04-19 10:21 UTC
