### ISSUE TITLE
CentOS 7.6 The system is unstable

### ISSUE THREAD

**Issue by xutao123777** [lathiat/avahi#360] opened 2021-11-04 10:42 UTC
The system is unstable, and the service needs to be restarted frequently with "systemctl restart avahi daemon"

**Comment by xutao123777** [comment] 2021-11-04 10:43
ping: pollux.local: Unknown name or service

**Comment by pemensik** [comment] 2022-10-04 19:10
Unstable responses might be caused by network equipment. For example on my home wifi multicast resolution is very unstable. When connected via ethernet cable it is rock stable. Can you share more about your network setup? Have you checked with wireshark that responses to your query arrives to your host?

**Comment by evverx** [comment] 2023-06-04 00:01
I don't think this bug report is actionable in its current form. I'll go ahead and close it but I think it can be reopened if the details are provided.

**Closed by evverx** 2023-06-04 00:01 UTC
Labels: needs-reporter-feedback
