### ISSUE TITLE
avahi-daemon: Host name conflict, retrying with apu2-2

### ISSUE THREAD

**Issue by iam-TJ** [lathiat/avahi#176] opened 2018-04-13 11:57 UTC
On a host with a single connected Ethernet interface I'm seeing frequent problems with the hostname changing.

Apr 12 20:45:41 apu2 avahi-daemon[697]: Server startup complete. Host name is apu2.local. Local service cookie is 2331567166.
...
Apr 12 22:10:05 apu2 avahi-daemon[697]: Host name conflict, retrying with apu2-2

hostname is apu2.

After some time it changes to apu-1 then apu-2 and so on. Restarting avahi-daemon returns to normal.

I also see this happening on hosts that go through a suspend/resume cycle. Upon resume the hostname changes - which breaks other hosts trying to reach them using mDNS name resolution.

Here's a log extract:

Apr 12 20:45:40 apu2 systemd[1]: Starting Avahi mDNS/DNS-SD Stack...
Apr 12 20:45:40 apu2 avahi-daemon[697]: Found user 'avahi' (UID 105) and group 'avahi' (GID 108).
Apr 12 20:45:40 apu2 avahi-daemon[697]: Successfully dropped root privileges.
Apr 12 20:45:40 apu2 avahi-daemon[697]: avahi-daemon 0.7 starting up.
Apr 12 20:45:40 apu2 avahi-daemon[697]: Successfully called chroot().
Apr 12 20:45:40 apu2 avahi-daemon[697]: Successfully dropped remaining capabilities.
Apr 12 20:45:40 apu2 avahi-daemon[697]: No service file found in /etc/avahi/services.
Apr 12 20:45:40 apu2 avahi-daemon[697]: Joining mDNS multicast group on interface lo.IPv6 with address ::1.
Apr 12 20:45:40 apu2 avahi-daemon[697]: New relevant interface lo.IPv6 for mDNS.
Apr 12 20:45:40 apu2 avahi-daemon[697]: Joining mDNS multicast group on interface lo.IPv4 with address 127.0.0.1.
Apr 12 20:45:40 apu2 avahi-daemon[697]: New relevant interface lo.IPv4 for mDNS.
Apr 12 20:45:40 apu2 avahi-daemon[697]: Network interface enumeration completed.
Apr 12 20:45:40 apu2 avahi-daemon[697]: Registering new address record for ::1 on lo.*.
Apr 12 20:45:40 apu2 avahi-daemon[697]: Registering new address record for 127.0.0.1 on lo.IPv4.
Apr 12 20:45:40 apu2 systemd[1]: Started Avahi mDNS/DNS-SD Stack.

Apr 12 20:45:41 apu2 avahi-daemon[697]: Server startup complete. Host name is apu2.local. Local service cookie is 2331567166.

Apr 12 20:45:43 apu2 avahi-daemon[697]: Joining mDNS multicast group on interface enp3s0.IPv4 with address 10.254.1.79.
Apr 12 20:45:43 apu2 avahi-daemon[697]: New relevant interface enp3s0.IPv4 for mDNS.
Apr 12 20:45:43 apu2 avahi-daemon[697]: Registering new address record for 10.254.1.79 on enp3s0.IPv4.
Apr 12 20:45:44 apu2 avahi-daemon[697]: Joining mDNS multicast group on interface enp3s0.IPv6 with address fe80::20d:b9ff:fe4a:722e.
Apr 12 20:45:44 apu2 avahi-daemon[697]: New relevant interface enp3s0.IPv6 for mDNS.
Apr 12 20:45:44 apu2 avahi-daemon[697]: Registering new address record for fe80::20d:b9ff:fe4a:722e on enp3s0.*.
Apr 12 20:45:46 apu2 avahi-daemon[697]: Leaving mDNS multicast group on interface enp3s0.IPv6 with address fe80::20d:b9ff:fe4a:722e.
Apr 12 20:45:46 apu2 avahi-daemon[697]: Joining mDNS multicast group on interface enp3s0.IPv6 with address 2a02:8011:2007:0:20d:b9ff:fe4a:722e.
Apr 12 20:45:46 apu2 avahi-daemon[697]: Registering new address record for 2a02:8011:2007:0:20d:b9ff:fe4a:722e on enp3s0.*.
Apr 12 20:45:46 apu2 avahi-daemon[697]: Withdrawing address record for fe80::20d:b9ff:fe4a:722e on enp3s0.
Apr 12 20:45:47 apu2 avahi-daemon[697]: Registering new address record for 2a02:8011:2007::3 on enp3s0.*.
Apr 12 21:12:11 apu2 avahi-daemon[697]: Joining mDNS multicast group on interface lxdbr0.IPv6 with address fe80::4456:4ff:fe39:2a08.
Apr 12 21:12:11 apu2 avahi-daemon[697]: New relevant interface lxdbr0.IPv6 for mDNS.
Apr 12 21:12:11 apu2 avahi-daemon[697]: Registering new address record for fe80::4456:4ff:fe39:2a08 on lxdbr0.*.
Apr 12 21:12:11 apu2 avahi-daemon[697]: Joining mDNS multicast group on interface lxdbr0.IPv4 with address 10.95.67.1.
Apr 12 21:12:11 apu2 avahi-daemon[697]: New relevant interface lxdbr0.IPv4 for mDNS.
Apr 12 21:12:11 apu2 avahi-daemon[697]: Registering new address record for 10.95.67.1 on lxdbr0.IPv4.
Apr 12 21:12:12 apu2 avahi-daemon[697]: Leaving mDNS multicast group on interface lxdbr0.IPv6 with address fe80::4456:4ff:fe39:2a08.
Apr 12 21:12:12 apu2 avahi-daemon[697]: Joining mDNS multicast group on interface lxdbr0.IPv6 with address fd42:781f:52e5:6398::1.
Apr 12 21:12:12 apu2 avahi-daemon[697]: Registering new address record for fd42:781f:52e5:6398::1 on lxdbr0.*.
Apr 12 21:12:12 apu2 avahi-daemon[697]: Withdrawing address record for fe80::4456:4ff:fe39:2a08 on lxdbr0.
Apr 12 22:02:52 apu2 avahi-daemon[697]: Interface lxdbr0.IPv6 no longer relevant for mDNS.
Apr 12 22:02:52 apu2 avahi-daemon[697]: Leaving mDNS multicast group on interface lxdbr0.IPv6 with address fd42:781f:52e5:6398::1.
Apr 12 22:02:52 apu2 avahi-daemon[697]: Interface lxdbr0.IPv4 no longer relevant for mDNS.
Apr 12 22:02:52 apu2 avahi-daemon[697]: Leaving mDNS multicast group on interface lxdbr0.IPv4 with address 10.95.67.1.
Apr 12 22:02:52 apu2 avahi-daemon[697]: Withdrawing address record for fd42:781f:52e5:6398::1 on lxdbr0.
Apr 12 22:02:52 apu2 avahi-daemon[697]: Withdrawing address record for 10.95.67.1 on lxdbr0.
Apr 12 22:10:04 apu2 avahi-daemon[697]: Joining mDNS multicast group on interface lxdbr0.IPv6 with address fe80::60c5:46ff:fea9:8177.
Apr 12 22:10:04 apu2 avahi-daemon[697]: New relevant interface lxdbr0.IPv6 for mDNS.
Apr 12 22:10:04 apu2 avahi-daemon[697]: Registering new address record for fe80::60c5:46ff:fea9:8177 on lxdbr0.*.
Apr 12 22:10:04 apu2 avahi-daemon[697]: Joining mDNS multicast group on interface lxdbr0.IPv4 with address 10.153.183.1.
Apr 12 22:10:04 apu2 avahi-daemon[697]: New relevant interface lxdbr0.IPv4 for mDNS.
Apr 12 22:10:04 apu2 avahi-daemon[697]: Registering new address record for 10.153.183.1 on lxdbr0.IPv4.
Apr 12 22:10:05 apu2 avahi-daemon[697]: Leaving mDNS multicast group on interface lxdbr0.IPv6 with address fe80::60c5:46ff:fea9:8177.
Apr 12 22:10:05 apu2 avahi-daemon[697]: Joining mDNS multicast group on interface lxdbr0.IPv6 with address fd42:178d:2999:880d::1.
Apr 12 22:10:05 apu2 avahi-daemon[697]: Registering new address record for fd42:178d:2999:880d::1 on lxdbr0.*.
Apr 12 22:10:05 apu2 avahi-daemon[697]: Withdrawing address record for fe80::60c5:46ff:fea9:8177 on lxdbr0.
Apr 12 22:10:05 apu2 avahi-daemon[697]: Withdrawing address record for 10.153.183.1 on lxdbr0.
Apr 12 22:10:05 apu2 avahi-daemon[697]: Withdrawing address record for 2a02:8011:2007::3 on enp3s0.
Apr 12 22:10:05 apu2 avahi-daemon[697]: Withdrawing address record for 2a02:8011:2007:0:20d:b9ff:fe4a:722e on enp3s0.
Apr 12 22:10:05 apu2 avahi-daemon[697]: Withdrawing address record for 10.254.1.79 on enp3s0.
Apr 12 22:10:05 apu2 avahi-daemon[697]: Withdrawing address record for ::1 on lo.
Apr 12 22:10:05 apu2 avahi-daemon[697]: Withdrawing address record for 127.0.0.1 on lo.

Apr 12 22:10:05 apu2 avahi-daemon[697]: Host name conflict, retrying with apu2-2

Apr 12 22:10:05 apu2 avahi-daemon[697]: Registering new address record for fd42:178d:2999:880d::1 on lxdbr0.*.
Apr 12 22:10:05 apu2 avahi-daemon[697]: Registering new address record for 10.153.183.1 on lxdbr0.IPv4.
Apr 12 22:10:05 apu2 avahi-daemon[697]: Registering new address record for 2a02:8011:2007::3 on enp3s0.*.
Apr 12 22:10:05 apu2 avahi-daemon[697]: Registering new address record for 2a02:8011:2007:0:20d:b9ff:fe4a:722e on enp3s0.*.
Apr 12 22:10:05 apu2 avahi-daemon[697]: Registering new address record for 10.254.1.79 on enp3s0.IPv4.
Apr 12 22:10:05 apu2 avahi-daemon[697]: Registering new address record for ::1 on lo.*.
Apr 12 22:10:05 apu2 avahi-daemon[697]: Registering new address record for 127.0.0.1 on lo.IPv4.
Apr 12 22:10:06 apu2 avahi-daemon[697]: Server startup complete. Host name is apu2-2.local. Local service cookie is 2331567166.
Apr 12 22:46:38 apu2 avahi-daemon[697]: Joining mDNS multicast group on interface lxcbr0.IPv4 with address 10.0.3.1.
Apr 12 22:46:38 apu2 avahi-daemon[697]: New relevant interface lxcbr0.IPv4 for mDNS.
Apr 12 22:46:38 apu2 avahi-daemon[697]: Registering new address record for 10.0.3.1 on lxcbr0.IPv4.
Apr 12 22:50:54 apu2 avahi-daemon[697]: Joining mDNS multicast group on interface vethXHC8P9.IPv6 with address fe80::fcf2:69ff:fe35:a749.
Apr 12 22:50:54 apu2 avahi-daemon[697]: New relevant interface vethXHC8P9.IPv6 for mDNS.
Apr 12 22:50:54 apu2 avahi-daemon[697]: Registering new address record for fe80::fcf2:69ff:fe35:a749 on vethXHC8P9.*.
Apr 13 11:14:05 apu2 systemd[1]: Stopping Avahi mDNS/DNS-SD Stack...

**Comment by lathiat** [comment] 2018-04-14 04:58
This is a duplicate of #117

**Closed** 2018-04-14 04:59 UTC
Labels: duplicate

**Comment by ajtdnta** [comment] 2019-05-16 05:25
there may be a same domain name within a LAN,  you can stop the other service by  commond 'systemctl disable avahi-daemon ; systemctl stop avahi-daemon' with  root privilege
