### ISSUE TITLE
mDNS over primary and subinterface

### ISSUE THREAD

**Issue by dfe-mouchet** [lathiat/avahi#528] opened 2023-11-16 16:16 UTC
Hi, I am running avahi-daemon over a primary interface br0 192.168.244.50/24 and a subinterface br0:1 192.168.10.50/24.
I enabled use-ipv4=yes use-ipv6=no and allow-interfaces=br0 in avahi-daemon.conf
From the log output attached, it seems that:
* the mDNS multicast group on interface br0 is actually joined with the address of br0:1 192.168.10.50
* both 192.168.10.50 and 192.168.244.50 are registered as record for br0

Is it the expected behaviour ?

[ifconfig_and_log.txt](https://github.com/lathiat/avahi/files/13380020/ifconfig_and_log.txt)

**Comment by evverx** [comment] 2023-11-16 16:29
Looks like it's a duplicate of https://github.com/lathiat/avahi/pull/115. Could you apply that patch to see if it works?

**Comment by evverx** [comment] 2023-11-17 02:35
I'm pretty sure it's a duplicate of https://github.com/lathiat/avahi/pull/115, https://github.com/lathiat/avahi/issues/103 and https://github.com/lathiat/avahi/issues/373. Since it's already tracked I'll go ahead and close it.

**Closed by evverx** 2023-11-17 02:35 UTC
Labels: duplicate, needs-reporter-feedback

**Comment by dfe-mouchet** [comment] 2023-11-17 16:22
Thanks @evverx for your quick reply, the patch you mentioned does work.

**Comment by dfe-mouchet** [comment] 2023-11-20 10:27
Exactly, `allow-interfaces=br0` was enough for my use case, `deny-interfaces=br0:1` can be also used, but `allow-interfaces=br0:1` does not work.
