### ISSUE TITLE
avahi let's 2 machine have the same .local address which is creating an issue.

### ISSUE THREAD

**Issue by jab5263** [lathiat/avahi#211] opened 2018-12-18 04:44 UTC
The issues is that if 2 devices(machine1 and machine2) have the same hostname in this network say "NameA" then avahi instead of appending "-2" to the hostname on one of the devices for making it accessible via .local address simply assign it to that machine i.e if ip of machine1 is 192.168.1.12, machine2 is 192.168.1.13 and machine3 is 192.168.1.14 and machine1 and machine2 have same hostname i.e "NameA" , now if i ssh into machine1 and do ping NameA.local it returns the ip 192.168.1.12 , whereas if i ssh into machine2 and do ping NameA.local it returns the ip 192.168.1.13 , whereas if i ssh into machine3 and do ping NameA.local it returns me the ip of any 1 machine (which is fine) , the issue is that why 2 machines in the network are using the same i.e "NameA.local" as this creating a lot of issues and why is avahi even allowing the 2nd machine to take up that name when the name is already taken by another machine ?

I am running 2 avahi stacks as of now on every device, 1 in the host machine so that it can access .local addresses and another in a container which is present in that host machine , which helps the container resolve the .local addresses , is it totally because of that which makes avahi-mdns unreliable and creating the issue  ? if this is the case i apologise for creating an 'issue'.
thanks

**Comment by jab5263** [comment] 2018-12-18 08:08
I tested after stopping the avahi in the container and doesn't face the issue anymore. Any idea what exaclty is causing this and how can i use the avahi-daemon in the host to query for ip addresses from inside the docker container ? basically like querying the daemon from external sources.
This is basically not something which should be a git issue , but i am not aware of any other better means  to ask my queries am sorry for that.
thanks

**Comment by lathiat** [comment] 2019-02-05 05:37
It sounds like the problem is that the containers aren't talking to the entire local network, only the host that it is on.

Is the container actually bridged (ethernet bridged) to the real network, or does it just have an IP local to the host it is on?

If it's not bridged, the containers won't see the other network nodes and won't be able to do hostname conflict resolution with them. Effectively in this case, the 'host' is on two separte networks - one with the local LAN and one with the container. With mDNS, there is no guarantee that hostnames are unique on multiple networks and you can specifically have a collision and will randomly get an IP of either of them unless you specify the interface scope. 

What kind of container is on the host, e.g. lxd, docker, etc - and how is the networking configured?

**Comment by jab5263** [comment] 2019-02-06 11:45
The container service on host is of docker , the docker container is basically using the host's network stack only, IDK what caused this issue but I found a way around this and am not facing this anymore , but I was not able to make mDNS queries from inside container unless I run a seperate avahi-daemon inside the container too (which makes it unreliable and ultimately create a lot of issues).

APART From this issue,
Just wanted to confirm that if there are  2 devices on the same network having the same host-name then they avahi will automatically append '-1' or '-2' and so on.. to their names right ?
As I am facing an issue , where 2 devices on the same network , which are able to ping each other  and have the same host-name are having the same  '.local' name too. 
PS : They are trying to change their hostnames continuously.

**Comment by evverx** [comment] 2023-11-13 04:22
> I was not able to make mDNS queries from inside container unless I run a seperate avahi-daemon inside the container too

If containers have their own network interfaces in their own network netspaces avahi should run inside those containers to make it work.

> Just wanted to confirm that if there are 2 devices on the same network having the same host-name then they avahi will automatically append '-1' or '-2' and so on.. to their names right ?

That's correct. Generally it happens when conflicts occur.

> PS : They are trying to change their hostnames continuously.

It looks like the avahi reflector with the "reflect-ipv" setting set to "yes" was set up somewhere on the host to I assume forward mDNS packets between containers and that setting isn't recommended. Spurious name conflicts are tracked elsewhere.

Anyway I'll go ahead and close this issue because as far as I understand the original question was answered as far as I can see and the containers started talking to each other and triggered conflicts.

**Closed by evverx** 2023-11-13 04:22 UTC
Labels: question
