### ISSUE TITLE
mediaserverd: SetRate 1 FAILURE

### ISSUE THREAD

**Issue by cpoetter** [lathiat/avahi#223] opened 2019-04-29 16:35 UTC
Hi,

I setup Avahi as a Bonjour reflector for my HomePods. Unfortunately playing music only works sometimes in the network the HomePods are *not* in. The console for macOS shows the following errors:

```
error	18:13:40.701956 +0200	mediaserverd	BAE [0xB873] [0x98AE] SetRate 1 FAILURE for stream 0x2430 failure count: 1 err = -71976
error	18:13:40.817037 +0200	mediaserverd	BAE [0xB873] [0x98AE] SetRate 1 FAILURE for stream 0x2430 failure count: 2 err = -71976
...
error	18:13:43.936697 +0200	mediaserverd	BAE [0xB873] [0x98AE] SetRate 1 FAILURE for stream 0x2430 failure count: 50 err = -71976
error	18:13:43.936844 +0200	mediaserverd	### BAE [0xB873] [0x98AE] Stream 0x2430 hit too many (50) retries trying to set rate to 1, dissociating...
```

Does anybody know what the error might be?

Thanks for your help!

**Comment by evverx** [comment] 2023-10-22 17:18
It's hard to tell. Looking at the log my guess would be that the devices couldn't talk to each other. avahi reflected mDNS packets but apart from that the devices should have been able to talk to each other. Another guess would be that it could have been caused by https://github.com/lathiat/avahi/issues/379. Either way I don't think it's possible to track it down without logs/configs/pcaps. Closing.

**Closed by evverx** 2023-10-22 17:18 UTC
