### ISSUE TITLE
got Host name conflict, retrying with MyBridge-4B19-91 with version 0.6.32

### ISSUE THREAD

**Issue by mohamedkallel82** [lathiat/avahi#361] opened 2021-11-12 08:55 UTC
I have2 devices using avahi version0.6.32
1- first device is with mac address: 40:A3:6B:C7:4A:1D. the avahi start and succes to have host name:
Server startup complete. Host name is MyBridge-4A1D.local. Local service cookie is 2103367654.
2- second device start after the first one and have the mac address 40:A3:6B:C7:4B:19. but the second one fails to have hostname and here after the log I got:
Host name conflict, retrying with MYBridge-4B19-91

What I am missing? or this is an old issue in 0.6.32 and it is already fixed in other version?

**Comment by mvduin** [comment] 2021-12-01 13:27
Duplicate of issue #117

**Comment by pemensik** [comment] 2022-11-24 17:41
Yes, there is pull request pending, which should fix issue #117. I will close this issue, please follow PR #309 .

**Closed by pemensik** 2022-11-24 17:41 UTC
