### ISSUE TITLE
Segfault when accessing .local network

### ISSUE THREAD

**Issue by jmighion** [lathiat/avahi#391] opened 2022-08-07 18:58 UTC
```
Aug 07 11:55:01 nuc systemd[1]: Starting avahi-daemon.service - Avahi mDNS/DNS-SD Stack...
Aug 07 11:55:01 nuc systemd[1]: Starting pmlogger_check.service - Check pmlogger instances are running...
Aug 07 11:55:01 nuc avahi-daemon[46923]: Process 46707 died: No such process; trying to remove PID file. (/run/avahi-daemon//pid)
Aug 07 11:55:01 nuc avahi-daemon[46923]: Found user 'avahi' (UID 70) and group 'avahi' (GID 70).
Aug 07 11:55:01 nuc avahi-daemon[46923]: Successfully dropped root privileges.
Aug 07 11:55:01 nuc avahi-daemon[46923]: avahi-daemon 0.8 starting up.
Aug 07 11:55:01 nuc audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=pmlogger_check comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Aug 07 11:55:01 nuc systemd[1]: Started pmlogger_check.service - Check pmlogger instances are running.
Aug 07 11:55:01 nuc audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=avahi-daemon comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Aug 07 11:55:01 nuc avahi-daemon[46923]: Successfully called chroot().
Aug 07 11:55:01 nuc systemd[1]: Started avahi-daemon.service - Avahi mDNS/DNS-SD Stack.
Aug 07 11:55:01 nuc avahi-daemon[46923]: Successfully dropped remaining capabilities.
Aug 07 11:55:01 nuc avahi-daemon[46923]: No service file found in /etc/avahi/services.
Aug 07 11:55:01 nuc avahi-daemon[46923]: Joining mDNS multicast group on interface vnet0.IPv6 with address fe80::fc54:ff:fedd:98f9.
Aug 07 11:55:01 nuc avahi-daemon[46923]: New relevant interface vnet0.IPv6 for mDNS.
Aug 07 11:55:01 nuc avahi-daemon[46923]: Joining mDNS multicast group on interface virbr0.IPv4 with address 192.168.122.1.
Aug 07 11:55:01 nuc avahi-daemon[46923]: New relevant interface virbr0.IPv4 for mDNS.
Aug 07 11:55:01 nuc avahi-daemon[46923]: Joining mDNS multicast group on interface br0.IPv6 with address fe80::df8d:2dfa:7e77:7f4c.
Aug 07 11:55:01 nuc avahi-daemon[46923]: New relevant interface br0.IPv6 for mDNS.
Aug 07 11:55:01 nuc avahi-daemon[46923]: Joining mDNS multicast group on interface br0.IPv4 with address 192.168.1.100.
Aug 07 11:55:01 nuc avahi-daemon[46923]: New relevant interface br0.IPv4 for mDNS.
Aug 07 11:55:01 nuc avahi-daemon[46923]: Joining mDNS multicast group on interface lo.IPv6 with address ::1.
Aug 07 11:55:01 nuc avahi-daemon[46923]: New relevant interface lo.IPv6 for mDNS.
Aug 07 11:55:01 nuc avahi-daemon[46923]: Joining mDNS multicast group on interface lo.IPv4 with address 127.0.0.1.
Aug 07 11:55:01 nuc avahi-daemon[46923]: New relevant interface lo.IPv4 for mDNS.
Aug 07 11:55:01 nuc avahi-daemon[46923]: Network interface enumeration completed.
Aug 07 11:55:01 nuc avahi-daemon[46923]: Registering new address record for fe80::fc54:ff:fedd:98f9 on vnet0.*.
Aug 07 11:55:01 nuc avahi-daemon[46923]: Registering new address record for 192.168.122.1 on virbr0.IPv4.
Aug 07 11:55:01 nuc avahi-daemon[46923]: Registering new address record for fe80::df8d:2dfa:7e77:7f4c on br0.*.
Aug 07 11:55:01 nuc avahi-daemon[46923]: Registering new address record for 192.168.1.100 on br0.IPv4.
Aug 07 11:55:01 nuc avahi-daemon[46923]: Registering new address record for ::1 on lo.*.
Aug 07 11:55:01 nuc avahi-daemon[46923]: Registering new address record for 127.0.0.1 on lo.IPv4.
Aug 07 11:55:01 nuc audit[46923]: ANOM_ABEND auid=4294967295 uid=70 gid=70 ses=4294967295 subj=system_u:system_r:avahi_t:s0 pid=46923 comm="avahi-daemon" exe="/usr/sbin/avahi-daemon" sig=11 res=1
Aug 07 11:55:01 nuc kernel: avahi-daemon[46923]: segfault at 7fff0b080fe8 ip 00007fc3009becaf sp 00007fff0b080ff0 error 6 in libavahi-common.so.3.5.4[7fc3009ba000+6000]
Aug 07 11:55:01 nuc kernel: Code: 48 81 ec 00 04 00 00 64 48 8b 04 25 28 00 00 00 48 89 84 24 f8 03 00 00 31 c0 48 85 ff 74 39 48 89 e3 ba f6 03 00 00 48 89 de <e8> 1c bc ff ff 48 85 c0 74 08 48 89 df e8 cf bd ff ff 48 8b 94 24
Aug 07 11:55:01 nuc audit: BPF prog-id=124 op=LOAD
Aug 07 11:55:01 nuc audit: BPF prog-id=125 op=LOAD
Aug 07 11:55:01 nuc audit: BPF prog-id=126 op=LOAD
Aug 07 11:55:01 nuc audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=systemd-coredump@6-47048-0 comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Aug 07 11:55:01 nuc systemd[1]: Started systemd-coredump@6-47048-0.service - Process Core Dump (PID 47048/UID 0).
Aug 07 11:55:01 nuc [47126]: [164B blob data]
Aug 07 11:55:01 nuc systemd-coredump[47057]: [🡕] Process 46923 (avahi-daemon) of user 70 dumped core.

                                             Module linux-vdso.so.1 with build-id e677a5a72afa1b766a44e2eca24b15b30d8211e1
                                             Module libnss_systemd.so.2 with build-id 3f0865540ea4717fd0caf10c604d3543343a8588
                                             Metadata for module libnss_systemd.so.2 owned by FDO found: {
                                                     "type" : "rpm",
                                                     "name" : "systemd",
                                                     "version" : "250.8-1.fc36",
                                                     "architecture" : "x86_64",
                                                     "osCpe" : "cpe:/o:fedoraproject:fedora:36"
                                             }

                                             Module libnss_sss.so.2 with build-id ceded8951b6a8d21ac432aa830dbbb27de007669
                                             Metadata for module libnss_sss.so.2 owned by FDO found: {
                                                     "type" : "rpm",
                                                     "name" : "sssd",
                                                     "version" : "2.7.3-1.fc36",
                                                     "architecture" : "x86_64",
                                                     "osCpe" : "cpe:/o:fedoraproject:fedora:36"
                                             }

                                             Module libgpg-error.so.0 with build-id a53c231739d55cc39b97e28c36cd8b3e58a8f8f8
                                             Metadata for module libgpg-error.so.0 owned by FDO found: {
                                                     "type" : "rpm",
                                                     "name" : "libgpg-error",
                                                     "version" : "1.45-1.fc36",
                                                     "architecture" : "x86_64",
                                                     "osCpe" : "cpe:/o:fedoraproject:fedora:36"
                                             }

                                             Module libgcc_s.so.1 with build-id 1e82df1fa0e0de4d8382b75c0fa730e0672f1a47
                                             Module libgcrypt.so.20 with build-id ab80eae398f8814c7dc7bfc27fa3724491a47294
                                             Stack trace of thread 46923:
                                             #0  0x00007fc3009becaf avahi_normalize_name_strdup (libavahi-common.so.3 + 0x7caf)
                                             #1  0x00007fc3009977f4 avahi_key_new (libavahi-core.so.7 + 0x1c7f4)
                                             #2  0x00007fc30099bb67 lookup_handle_cname (libavahi-core.so.7 + 0x20b67)
                                             #3  0x00007fc30099c072 lookup_multicast_callback (libavahi-core.so.7 + 0x21072)
                                             #4  0x00007fc3009a00bb scan_cache_callback (libavahi-core.so.7 + 0x250bb)
                                             #5  0x00007fc30098b193 avahi_cache_walk (libavahi-core.so.7 + 0x10193)
                                             #6  0x00007fc3009a4647 scan_interface_callback (libavahi-core.so.7 + 0x29647)
                                             #7  0x00007fc30098a290 avahi_interface_monitor_walk (libavahi-core.so.7 + 0xf290)
                                             #8  0x00007fc3009a476c avahi_multicast_lookup_engine_scan_cache (libavahi-core.so.7 + 0x2976c)
                                             #9  0x00007fc30099b931 lookup_go (libavahi-core.so.7 + 0x20931)
                                             #10 0x00007fc30099bbb7 lookup_handle_cname (libavahi-core.so.7 + 0x20bb7)
                                             #11 0x00007fc30099c072 lookup_multicast_callback (libavahi-core.so.7 + 0x21072)
                                             #12 0x00007fc3009a00bb scan_cache_callback (libavahi-core.so.7 + 0x250bb)
                                             #13 0x00007fc30098b193 avahi_cache_walk (libavahi-core.so.7 + 0x10193)
                                             #14 0x00007fc3009a4647 scan_interface_callback (libavahi-core.so.7 + 0x29647)
                                             #15 0x00007fc30098a290 avahi_interface_monitor_walk (libavahi-core.so.7 + 0xf290)
                                             #16 0x00007fc3009a476c avahi_multicast_lookup_engine_scan_cache (libavahi-core.so.7 + 0x2976c)
                                             #17 0x00007fc30099b931 lookup_go (libavahi-core.so.7 + 0x20931)
                                             #18 0x00007fc30099bbb7 lookup_handle_cname (libavahi-core.so.7 + 0x20bb7)
                                             #19 0x00007fc30099c072 lookup_multicast_callback (libavahi-core.so.7 + 0x21072)
                                             #20 0x00007fc3009a00bb scan_cache_callback (libavahi-core.so.7 + 0x250bb)
                                             #21 0x00007fc30098b193 avahi_cache_walk (libavahi-core.so.7 + 0x10193)
                                             #22 0x00007fc3009a4647 scan_interface_callback (libavahi-core.so.7 + 0x29647)
                                             #23 0x00007fc30098a290 avahi_interface_monitor_walk (libavahi-core.so.7 + 0xf290)
                                             #24 0x00007fc3009a476c avahi_multicast_lookup_engine_scan_cache (libavahi-core.so.7 + 0x2976c)
                                             #25 0x00007fc30099b931 lookup_go (libavahi-core.so.7 + 0x20931)
                                             #26 0x00007fc30099bbb7 lookup_handle_cname (libavahi-core.so.7 + 0x20bb7)
                                             #27 0x00007fc30099c072 lookup_multicast_callback (libavahi-core.so.7 + 0x21072)
                                             #28 0x00007fc3009a00bb scan_cache_callback (libavahi-core.so.7 + 0x250bb)
                                             #29 0x00007fc30098b193 avahi_cache_walk (libavahi-core.so.7 + 0x10193)
                                             #30 0x00007fc3009a4647 scan_interface_callback (libavahi-core.so.7 + 0x29647)
                                             #31 0x00007fc30098a290 avahi_interface_monitor_walk (libavahi-core.so.7 + 0xf290)
                                             #32 0x00007fc3009a476c avahi_multicast_lookup_engine_scan_cache (libavahi-core.so.7 + 0x2976c)
                                             #33 0x00007fc30099b931 lookup_go (libavahi-core.so.7 + 0x20931)
                                             #34 0x00007fc30099bbb7 lookup_handle_cname (libavahi-core.so.7 + 0x20bb7)
                                             #35 0x00007fc30099c072 lookup_multicast_callback (libavahi-core.so.7 + 0x21072)
                                             #36 0x00007fc3009a00bb scan_cache_callback (libavahi-core.so.7 + 0x250bb)
                                             #37 0x00007fc30098b193 avahi_cache_walk (libavahi-core.so.7 + 0x10193)
                                             #38 0x00007fc3009a4647 scan_interface_callback (libavahi-core.so.7 + 0x29647)
                                             #39 0x00007fc30098a290 avahi_interface_monitor_walk (libavahi-core.so.7 + 0xf290)
                                             #40 0x00007fc3009a476c avahi_multicast_lookup_engine_scan_cache (libavahi-core.so.7 + 0x2976c)
                                             #41 0x00007fc30099b931 lookup_go (libavahi-core.so.7 + 0x20931)
                                             #42 0x00007fc30099bbb7 lookup_handle_cname (libavahi-core.so.7 + 0x20bb7)
                                             #43 0x00007fc30099c072 lookup_multicast_callback (libavahi-core.so.7 + 0x21072)
                                             #44 0x00007fc3009a00bb scan_cache_callback (libavahi-core.so.7 + 0x250bb)
                                             #45 0x00007fc30098b193 avahi_cache_walk (libavahi-core.so.7 + 0x10193)
                                             #46 0x00007fc3009a4647 scan_interface_callback (libavahi-core.so.7 + 0x29647)
                                             #47 0x00007fc30098a290 avahi_interface_monitor_walk (libavahi-core.so.7 + 0xf290)
                                             #48 0x00007fc3009a476c avahi_multicast_lookup_engine_scan_cache (libavahi-core.so.7 + 0x2976c)
                                             #49 0x00007fc30099b931 lookup_go (libavahi-core.so.7 + 0x20931)
                                             #50 0x00007fc30099bbb7 lookup_handle_cname (libavahi-core.so.7 + 0x20bb7)
                                             #51 0x00007fc30099c072 lookup_multicast_callback (libavahi-core.so.7 + 0x21072)
                                             #52 0x00007fc3009a00bb scan_cache_callback (libavahi-core.so.7 + 0x250bb)
                                             #53 0x00007fc30098b193 avahi_cache_walk (libavahi-core.so.7 + 0x10193)
                                             #54 0x00007fc3009a4647 scan_interface_callback (libavahi-core.so.7 + 0x29647)
                                             #55 0x00007fc30098a290 avahi_interface_monitor_walk (libavahi-core.so.7 + 0xf290)
                                             #56 0x00007fc3009a476c avahi_multicast_lookup_engine_scan_cache (libavahi-core.so.7 + 0x2976c)
                                             #57 0x00007fc30099b931 lookup_go (libavahi-core.so.7 + 0x20931)
                                             #58 0x00007fc30099bbb7 lookup_handle_cname (libavahi-core.so.7 + 0x20bb7)
                                             #59 0x00007fc30099c072 lookup_multicast_callback (libavahi-core.so.7 + 0x21072)
                                             #60 0x00007fc3009a00bb scan_cache_callback (libavahi-core.so.7 + 0x250bb)
                                             #61 0x00007fc30098b193 avahi_cache_walk (libavahi-core.so.7 + 0x10193)
                                             #62 0x00007fc3009a4647 scan_interface_callback (libavahi-core.so.7 + 0x29647)
                                             #63 0x00007fc30098a290 avahi_interface_monitor_walk (libavahi-core.so.7 + 0xf290)
                                             ELF object binary architecture: AMD x86-64
```

This only happens when I try to access a host on my local network like `curl <hostname>.local`.

**Comment by pemensik** [comment] 2022-10-04 19:19
Can you please specify your distribution and package version of avahi?

**Comment by jmighion** [comment] 2022-10-04 20:03
```
[root@nuc ~]# systemctl status avahi-daemon.socket
● avahi-daemon.socket - Avahi mDNS/DNS-SD Stack Activation Socket
     Loaded: loaded (/usr/lib/systemd/system/avahi-daemon.socket; enabled; vendor preset: enabled)
     Active: active (listening) since Sat 2022-10-01 02:37:24 PDT; 3 days ago
      Until: Sat 2022-10-01 02:37:24 PDT; 3 days ago
   Triggers: ● avahi-daemon.service
     Listen: /run/avahi-daemon/socket (Stream)
     CGroup: /system.slice/avahi-daemon.socket

Oct 01 02:37:24 nuc systemd[1]: Listening on avahi-daemon.socket - Avahi mDNS/DNS-SD Stack Activation Socket.
[root@nuc ~]# systemctl status avahi-daemon.service
× avahi-daemon.service - Avahi mDNS/DNS-SD Stack
     Loaded: loaded (/usr/lib/systemd/system/avahi-daemon.service; enabled; vendor preset: enabled)
     Active: failed (Result: core-dump) since Tue 2022-10-04 12:59:47 PDT; 1min 8s ago
TriggeredBy: ● avahi-daemon.socket
    Process: 1023 ExecStart=/usr/sbin/avahi-daemon -s (code=dumped, signal=SEGV)
   Main PID: 1023 (code=dumped, signal=SEGV)
     Status: "avahi-daemon 0.8 starting up."
        CPU: 1min 2.486s

Oct 01 02:37:59 nuc avahi-daemon[1023]: Registering new address record for 192.168.1.100 on br0.IPv4.
Oct 01 02:38:01 nuc avahi-daemon[1023]: Joining mDNS multicast group on interface virbr0.IPv4 with address 192.168.122.1.
Oct 01 02:38:01 nuc avahi-daemon[1023]: New relevant interface virbr0.IPv4 for mDNS.
Oct 01 02:38:01 nuc avahi-daemon[1023]: Registering new address record for 192.168.122.1 on virbr0.IPv4.
Oct 01 02:38:04 nuc avahi-daemon[1023]: Joining mDNS multicast group on interface vnet0.IPv6 with address fe80::fc54:ff:fedd>
Oct 01 02:38:04 nuc avahi-daemon[1023]: New relevant interface vnet0.IPv6 for mDNS.
Oct 01 02:38:04 nuc avahi-daemon[1023]: Registering new address record for fe80::fc54:ff:fedd:98f9 on vnet0.*.
Oct 04 12:59:47 nuc systemd[1]: avahi-daemon.service: Main process exited, code=dumped, status=11/SEGV
Oct 04 12:59:47 nuc systemd[1]: avahi-daemon.service: Failed with result 'core-dump'.
Oct 04 12:59:47 nuc systemd[1]: avahi-daemon.service: Consumed 1min 2.486s CPU time.


[root@nuc ~]# uname -a
Linux nuc 5.19.12-200.fc36.x86_64 #1 SMP PREEMPT_DYNAMIC Wed Sep 28 17:11:05 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

[root@nuc ~]# dnf info avahi
Installed Packages
Name         : avahi
Version      : 0.8
Release      : 15.fc36
Architecture : x86_64
Size         : 1.2 M
Source       : avahi-0.8-15.fc36.src.rpm
Repository   : @System
From repo    : fedora
Summary      : Local network service discovery
URL          : http://avahi.org
License      : LGPLv2+
Description  : Avahi is a system which facilitates service discovery on
             : a local network -- this means that you can plug your laptop or
             : computer into a network and instantly be able to view other people who
             : you can chat with, find printers to print to or find files being
             : shared. This kind of technology is already found in MacOS X (branded
             : 'Rendezvous', 'Bonjour' and sometimes 'ZeroConf') and is very
             : convenient.
```

**Comment by pemensik** [comment] 2022-10-04 20:27
Please consider also filling bug on https://bugzilla.redhat.com, product Fedora and including the link to this upstream issue. It would require backport on Fedora even if fixed here. I haven't found any similar report there. It might help if you used ABRT tool to report your crash, including possible core dump.

**Comment by pemensik** [comment] 2022-12-07 22:29
Yes, closing as duplicate of bug #78, even when this report is easier to process, because of better inline format.

**Closed by pemensik** 2022-12-07 22:29 UTC
Labels: bug, duplicate
